---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clusterclass
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters/clusterclass
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusterclass
  targetNamespace: default

