---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-cluster
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/abashir236/fleet-infra

