---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster
  namespace: default
spec:
  chart:
    spec:
      chart: ./clusters/helm-cluster
      sourceRef:
  dependsOn:
    - name: helm-clusterclass
  interval: 30s
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-cluster
  targetNamespace: default

