---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster
  namespace: default
spec:
  dependsOn:
    - name: helm-clusterclass
  interval: 30s
  path: "./clusters/helm-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-cluster
  targetNamespace: default

