---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-class
  interval: 30s
  path: "./clusters/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default

