---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-class
  interval: 30s
  path: "./clusters/helm-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  targetNamespace: default

